---
# file: bigip_as3_app_gslb_onboard.yml
- name: Convert input CSV files content to a YAML vars file
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  vars_files:
    - "../files/gslb_app_onboard_vars.yml"

  tasks:
    - name: parse csv and make vars file
      command: "python {{vars_script_file}} -i {{input_csv_file}} -o {{output_yml_file}}"

- name: Build GSLB apps based on AS3 declaration
  hosts: bigip
  gather_facts: false
  connection: local

  vars_files:
    - "../files/gslb_app_onboard_vars.yml"
    - "{{output_yml_file}}"
 
  tasks:

  - name: Build JSON payload
    template: src="{{src_template_file}}" dest="{{dest_json_file}}"

  - name: Get an API token
    uri:
      url: "https://{{inventory_hostname}}:{{ bigip_port }}/mgmt/shared/authn/login"
      method: POST
      body:
        {
          "username": "{{ bigip_username }}",
          "password": "{{ bigip_password }}",
           "loginProviderName": "tmos"
        }
      status_code: 200
      body_format: json
      validate_certs: "{{ validate_certs }}"
    register: auth

  - name: Send AS3 request
    uri:
      url: "https://{{inventory_hostname}}:{{ bigip_port }}/mgmt/shared/appsvcs/declare"
      method: "POST"
      headers:
        X-F5-Auth-Token: "{{ auth['json']['token']['name'] }}"
      body_format: json
      body: "{{lookup('file','{{dest_json_file}}')}}"
      validate_certs: "{{ validate_certs }}"
      status_code: 200
    delegate_to: localhost

