---
# file: bigip_as3_clean_app.yml
- name: Clean up application from tenant
  hosts: bigip
  gather_facts: false
  connection: local

  tasks:

  - name: Get an API token
    uri:
      url: "https://{{inventory_hostname}}:{{ bigip_port }}/mgmt/shared/authn/login"
      method: POST
      body:
        {
          "username": "{{ bigip_username }}",
          "password": "{{ bigip_password }}",
           "loginProviderName": "tmos"
        }
      status_code: 200
      body_format: json
      validate_certs: "{{ validate_certs }}"
    register: auth

  - name: Send AS3 request
    uri:
      url: "https://{{inventory_hostname}}:{{ bigip_port }}/mgmt/shared/appsvcs/declare"
      method: "PATCH"
      headers:
        X-F5-Auth-Token: "{{ auth['json']['token']['name'] }}"
      body_format: json
      body: "{{lookup('file','as3_clean_app.json')}}"
      validate_certs: "{{ validate_certs }}"
      status_code: 200
    delegate_to: localhost

