---

- name: Fetch a qkview from the remote device
  hosts: bigip
  gather_facts: false
  
  tasks:
    - name: Fatch a qkview from the remote device
      bigip_qkview:
        exclude:
          - audit
          - secure
        dest: /tmp/localhost.localdomain.qkview
        provider:
          password: "{{ bigip_password }}"
          server: 10.1.1.243
          user: "{{ bigip_username }}"
          validate_certs: "no"
