---

- name: Fetch a ucs backup from the remote device
  hosts: bigip

  tasks:
    - name: Fatch a ucs backup from the remote device
      bigip_ucs_fetch:
        dest: /tmp/bigip.ucs
        password: "{{ bigip_password }}"
        server: 10.1.1.243
        user: "{{ bigip_username }}"
        validate_certs: "no"
      connection: local
      delegate_to: localhost
