---

- name: Upload absolute image to the BIG-IP
  hosts: bigip

  tasks:
    - name: Upload a BIG-IP image
      vars:
        image_type: release
      bigip_software_image:
        image: /home/f5/ansible-projects/files/BIGIP-13.1.1.2-0.0.4.iso
        provider:
          password: "{{ bigip_password }}" 
          server: 10.1.1.243
          user: "{{ bigip_username }}"
          validate_certs: "no"
      delegate_to: localhost
